export enum SanremoYOUMode {
  LISTENING = 'LISTENING',
  MANUAL_CONTROLLING = 'MANUAL_CONTROLLING',
  PROFILE_P1_CONTROLLING = 'PROFILE_P1_CONTROLLING',
  PROFILE_P2_CONTROLLING = 'PROFILE_P2_CONTROLLING',
  PROFILE_P3_CONTROLLING = 'PROFILE_P3_CONTROLLING',
}
