sonar.projectKey=beanconqueror
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=src/main.ts,src/polyfills.ts,src/test.ts,src/zone-flags.ts,src/app/**,src/components/**,src/popover/**,src/services/**,src/directive/**,src/enums/**,src/interfaces/**,src/models/**,src/native/**,src/generated/**,src/assets/**,src/environments/**,src/store_screens/**,src/classes/angular/**,src/classes/appEvent/**,src/classes/bean/**,src/classes/brew/**,src/classes/devices/**,src/classes/graph/**,src/classes/preparation/**,src/classes/preparationDevice/**,src/classes/roasting-machine/**,src/classes/server/**,src/classes/settings/**,src/classes/version/**,src/classes/storageClass.ts
sonar.coverage.exclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
