export enum BEAN_ACTION {

  DETAIL = 'DETAIL',
  REPEAT = 'REPEAT',
  EDIT = 'EDIT',
  DELETE = 'DELETE',
  BEANS_CONSUMED = 'BEANS_CONSUMED',
  PHOTO_GALLERY = 'PHOTO_GALLERY',
  TOGGLE_FAVOURITE = 'TOGGLE_FAVOURITE',
  SHARE = 'SHARE',
  REFRESH_DATA = 'REFRESH_DATA'
}
