export enum BEAN_ACTION {

  DETAIL = 'DETAIL',
  INFORMATION = 'INFORMATION',
  REPEAT = 'REPEAT',
  EDIT = 'EDIT',
  DELETE = 'DELETE',
  BEANS_CONSUMED = 'BEANS_CONSUMED',
  PHOTO_GALLERY = 'PHOTO_GALLERY'
}
