export enum BEAN_SORT_AFTER {
  UNKOWN = 'UNKOWN',
  NAME = 'NAME',
  ROASTER = 'ROASTER',
  ROASTING_DATE = 'ROASTING DATE',
  CREATION_DATE = 'CREATION DATE',
  PURCHASE_DATE = 'PURCHASE DATE',
  RATING = 'RATING',
  BEAN_AGE = 'BEAN AGE',
}
