export enum BEAN_CODE_ACTION {
  START_BREW = 'START_BREW',
  START_BREW_CHOOSE_PREPARATION = 'START_BREW_CHOOSE_PREPARATION',
  DETAIL = 'DETAIL',
  EDIT = 'EDIT',
  CHOOSE_ACTION = 'CHOOSE_ACTION',
}
