export enum BEAN_FREEZING_STORAGE_ENUM {
  UNKNOWN = 'UNKNOWN',
  COFFEE_BAG = 'COFFEE_BAG',
  COFFEE_JAR = 'COFFEE_JAR',
  ZIP_LOCK = 'ZIP_LOCK',
  VACUUM_SEALED = 'VACUUM_SEALED',
  TUBE = 'TUBE',
}
