export enum AppEventType {
  STORAGE_CHANGED = 'STORAGE_CHANGED',
  BLUETOOTH_SCALE_DISCONNECT = 'BLUETOOTH_SCALE_DISCONNECT',
  BLUETOOTH_PRESSURE_DEVICE_DISCONNECT = 'BLUETOOTH_PRESSURE_DEVICE_DISCONNECT',
  BLUETOOTH_TEMPERATURE_DEVICE_DISCONNECT = 'BLUETOOTH_TEMPERATURE_DEVICE_DISCONNECT',
}
