export enum PREPARATION_FUNCTION_PIPE_ENUM {
  HAS_PHOTOS = 'HAS_PHOTOS',
  GET_ICON = 'GET_ICON',
  HAS_DEVICE_CONNECTION = 'HAS_DEVICE_CONNECTION',
  IS_XENIA_CONNECTION = 'IS_XENIA_CONNECTION',
  IS_SANREMO_CONNECTION = 'IS_SANREMO_CONNECTION',
}
