export enum PREPARATION_TYPES {

  CUSTOM_PREPARATION = 'CUSTOM_PREPARATION',
  AEROPRESS = 'AEROPRESS',
  V60 = 'V60',
  CHEMEX = 'CHEMEX',
  BIALETTI = 'BIALETTI',
  PORTAFILTER = 'PORTAFILTER',
  KALITA_WAVE = 'KALITA_WAVE',
  FRENCH_PRESS = 'FRENCH_PRESS',

  TURKISH = 'TURKISH',
  AEROPRESS_INVERTED = 'AEROPRESS_INVERTED',
  DRIPPER = 'DRIPPER',
  DELTER_PRESS = 'DELTER_PRESS',
  COLD_BREW = 'COLD_BREW',
  BLUE_DRIPPER = 'BLUE_DRIPPER'

}
