export enum PREPARATION_TYPES {

  CUSTOM_PREPARATION = 'CUSTOM_PREPARATION',
  AEROPRESS = 'AEROPRESS',
  V60 = 'V60',
  CHEMEX = 'CHEMEX',
  BIALETTI = 'BIALETTI',
  PORTAFILTER = 'PORTAFILTER',
  KALITA_WAVE = 'KALITA_WAVE',
  FRENCH_PRESS = 'FRENCH_PRESS'

}
