export enum PREPARATION_ACTION {
  CUSTOM_PARAMETERS = 'CUSTOM_PARAMETERS',
  DETAIL = 'DETAIL',
  REPEAT = 'REPEAT',
  EDIT = 'EDIT',
  DELETE = 'DELETE',
  ARCHIVE = 'ARCHIVE',
  PHOTO_GALLERY = 'PHOTO_GALLERY'
}
