export enum GREEN_BEAN_ACTION {
  DETAIL = 'DETAIL',
  TRANSFER_ROAST = 'TRANSFER_ROAST',
  REPEAT = 'REPEAT',
  EDIT = 'EDIT',
  DELETE = 'DELETE',
  BEANS_CONSUMED = 'BEANS_CONSUMED',
  PHOTO_GALLERY = 'PHOTO_GALLERY',
}
