export enum CLOUD_AI_PROVIDER_ENUM {
  APPLE_INTELLIGENCE = 'APPLE_INTELLIGENCE',
  OPENAI = 'OPENAI',
  GOOGLE = 'GOOGLE',
  ANTHROPIC = 'ANTHROPIC',
  MISTRAL = 'MISTRAL',
  OPENROUTER = 'OPENROUTER',
  CUSTOM = 'CUSTOM',
}
