export enum BREW_FUNCTION_PIPE_ENUM {
  GET_EXTRACTION_YIELD = 'GET_EXTRACTION_YIELD',
  GET_BREW_RATIO = 'GET_BREW_RATIO',
  FORMATTED_TOTAL_COFFEE_TEMPERATURE_TIME = 'FORMATTED_TOTAL_COFFEE_TEMPERATURE_TIME',
  FORMATTED_TOTAL_COFFEE_BLOOMING_TIME = 'FORMATTED_TOTAL_COFFEE_BLOOMING_TIME',
  FORMATTED_TOTAL_COFFEE_FIRST_DRIP_TIME = 'FORMATTED_TOTAL_COFFEE_FIRST_DRIP_TIME',
  GET_CALCULATED_BEAN_AGE = 'GET_CALCULATED_BEAN_AGE',
  IS_ARCHIVED = 'IS_ARCHIVED',
}
