export enum BREW_ACTION {

  POST = 'POST',
  REPEAT = 'REPEAT',
  DETAIL = 'DETAIL',
  EDIT = 'EDIT',
  DELETE = 'DELETE',
  PHOTO_GALLERY = 'PHOTO_GALLERY',
  CUPPING = 'CUPPING',
  SHOW_MAP_COORDINATES = 'SHOW_MAP_COORDINATES',
}
